2022-11-03 06:52:50,279 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'images']
2022-11-03 06:52:50,680 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'images', 'list']
2022-11-03 06:52:50,691 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/?recursive=true
2022-11-03 06:52:50,694 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2022-11-03 06:52:50,696 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2022-11-03 06:52:50,696 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/token
2022-11-03 06:52:50,699 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 267
2022-11-03 06:52:50,711 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/?recursive=true
2022-11-03 06:52:50,713 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2022-11-03 06:52:50,714 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2022-11-03 06:52:50,715 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/token
2022-11-03 06:52:50,717 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 267
2022-11-03 06:52:50,913 DEBUG    root            Running [gcloud.container.images.list] with arguments: [--repository: "gcr.io/insight-tool-321814w"]
2022-11-03 06:52:50,916 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): gcr.io:443
2022-11-03 06:52:51,160 DEBUG    urllib3.connectionpool https://gcr.io:443 "GET /v2/ HTTP/1.1" 401 None
2022-11-03 06:52:51,166 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/?recursive=true
2022-11-03 06:52:51,168 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2022-11-03 06:52:51,169 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 155
2022-11-03 06:52:51,170 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/token
2022-11-03 06:52:51,172 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/554650739751-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 268
2022-11-03 06:52:51,237 DEBUG    urllib3.connectionpool https://gcr.io:443 "GET /v2/token?scope=repository%3Ainsight-tool-321814w%3Apull&service=gcr.io HTTP/1.1" 400 None
2022-11-03 06:52:51,238 DEBUG    root            (gcloud.container.images.list) Bad status during token exchange: 400
b'{"errors":[{"code":"UNKNOWN","message":"Project \'project:insight-tool-321814w\' not found or deleted."}]}'
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/images/util.py", line 477, in WrapExpectedDockerlessErrors
    yield
  File "/usr/lib/google-cloud-sdk/lib/surface/container/images/list.py", line 105, in Run
    with docker_image.FromRegistry(
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/containerregistry/client/v2_2/docker_image_.py", line 379, in __enter__
    self._transport = docker_http.Transport(
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/containerregistry/client/v2_2/docker_http_.py", line 208, in __init__
    self._Refresh()
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/containerregistry/client/v2_2/docker_http_.py", line 314, in _Refresh
    raise TokenRefreshException('Bad status during token exchange: %d\n%s' %
containerregistry.client.v2_2.docker_http_.TokenRefreshException: Bad status during token exchange: 400
b'{"errors":[{"code":"UNKNOWN","message":"Project \'project:insight-tool-321814w\' not found or deleted."}]}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/container/images/list.py", line 110, in Run
    return images
  File "/usr/lib/google-cloud-sdk/platform/bundledpythonunix/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/images/util.py", line 491, in WrapExpectedDockerlessErrors
    raise TokenRefreshError(six.text_type(err))
googlecloudsdk.api_lib.container.images.util.TokenRefreshError: Bad status during token exchange: 400
b'{"errors":[{"code":"UNKNOWN","message":"Project \'project:insight-tool-321814w\' not found or deleted."}]}'
2022-11-03 06:52:51,326 ERROR    root            (gcloud.container.images.list) Bad status during token exchange: 400
b'{"errors":[{"code":"UNKNOWN","message":"Project \'project:insight-tool-321814w\' not found or deleted."}]}'
